#!/usr/bin/perl

use strict;
use warnings;
use POSIX qw(strftime);

my $category = "chatter";
my $permalink = "";
if (scalar @ARGV == 1) {
    $permalink = $ARGV[0];
} elsif (scalar @ARGV == 2) {
    ($category, $permalink) = @ARGV;
} else {
    die "invalid parameters.";
}

my ($date,$time) = split / /,(strftime "%Y-%m-%d %H:%M:%S", localtime);
my $name = "./_posts/".$date."-".$permalink.".textile";
die "file exists.\n" if -e $name;

open FILE,">".$name or die "failed to open file";
print FILE <<eof;
---
layout: post
title: \"\"
category: $category
date: $date $time
---


eof
close FILE;

print $name."\n";
system("mousepad ".$name);
